title: "Balanced: Blog"
name: Balanced Blog
description: Balanced Blog
url: http://blog.balancedpayments.com
future: false

markdown: kramdown
pygments: true
permalink: /:title

lsi: false
paginate: 5

exclude:
- CNAME
