title: "Balanced: Blog"
name: Balanced Blog
description: Balanced Blog
url: http://blog.balancedpayments.com

markdown: maruku
pygments: true
permalink: /:title

lsi: true
paginate: 20

exclude:
- CNAME
